kind: pipeline
name: TA - Adapta - CI

steps:
- name: Build & Push
  image: plugins/docker
  settings:
    repo: str00bs/adapta
    tags:
    - ${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - tag

trigger:
  event:
  - tag

