services:
  database:
    image: postgres:17.3
    container_name: service-adapta-database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - adapta-net

  app:
    build: .
    container_name: service-adapta-app
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - adapta-net
    ports: 
      - "80:80"

networks:
  adapta-net:
    name: adapta-net
    external: false
