services:
  database:
    image: postgres:17.3
    container_name: service-adapta-database-2
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - adapta-net-2
    labels:
      - traefik.enable=false

  app:
    build: .
    container_name: service-adapta-app-2
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - adapta-net-2
      - proxy
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.adapta-2.tls=true
      - traefik.http.routers.adapta-2.tls.certresolver=letsencrypt
      - traefik.http.routers.adapta-2.entrypoints=https
      - traefik.http.routers.adapta-2.rule=Host(`${DOMAIN}`)
      # Services
      - traefik.http.services.adapta-2.loadbalancer.server.port=80

networks:
  adapta-net-2:
    name: adapta-net-2
    external: false
  proxy:
    external: true