services:
  database:
    image: postgres:17.3
    container_name: service-adapta-database-3
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - adapta-net-3
    labels:
      - traefik.enable=false

  app:
    build: .
    container_name: service-adapta-app-3
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - adapta-net-3
      - proxy
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.adapta-3.tls=true
      - traefik.http.routers.adapta-3.tls.certresolver=letsencrypt
      - traefik.http.routers.adapta-3.entrypoints=https
      - traefik.http.routers.adapta-3.rule=Host(`${DOMAIN}`)
      # Services
      - traefik.http.services.adapta-3.loadbalancer.server.port=80

networks:
  adapta-net-3:
    name: adapta-net-3
    external: false
  proxy:
    external: true