services:
  database:
    image: postgres:17.3
    container_name: service-adapta-database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    labels:
      - traefik.enable=false
    networks:
      - adapta-net

  app:
    image: str00bs/adapta:${BRANCH_NAME}
    container_name: service-adapta-app
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - adapta-net
      - proxy
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.adapta.tls=true
      - traefik.http.routers.adapta.tls.certresolver=letsencrypt
      - traefik.http.routers.adapta.entrypoints=https
      - traefik.http.routers.adapta.rule=Host(`${DOMAIN}`)
      # Services
      - traefik.http.services.adapta.loadbalancer.server.port=80

networks:
  adapta-net:
    name: adapta-net
    external: false
  proxy:
    external: true