[tool.poetry]
name = "acme"
version = "0.1.0"
description = "Technical Assignment - Adapta"
authors = ["Ada <github@adapdr.me>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.8"
pydantic = "^2.10.6"
pydantic-settings = "^2.7.1"
masonite-orm = "^2.24.0"
jinja2 = "^3.1.5"
uvicorn = "^0.34.0"


[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.0"
flake8 = "^7.1.2"
bandit = "^1.8.3"
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
